version: '3.7'


services:
  database_xy-inc:
    image: postgres
    container_name: database_xy-inc
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=database_xy-inc
    volumes:
      - pgdata:/data/postgres
    
  app:
    build: .
    container_name: backend
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_xy-inc
    depends_on:
      - database_xy-inc

volumes:
  pgdata:
    driver: local